Web.Mvc/Controllers/FriendController.cs
using Core.Base.Interface.Service;
using Core.Base.Model;
using Core.Base.Service;
using Infra.Data.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Mvc.Controllers
{
    [Authorize]
    public class FriendController : Controller
    {
        IFriendService _friendService;
        public FriendController(IFriendService friendService)
        {
            _friendService = friendService;
        }

        // GET: Friend
        public ActionResult Index()
        {
            return View(_friendService.GetAll());
        }

        // GET: Friend/Games/5
        public ActionResult Games(int id)
        {
            var friend = _friendService.GetFriend(id);
            return View(friend.Games);
        }

        // GET: Friend/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Friend/Create
        [HttpPost]
        public ActionResult Create(Friend friend)
        {
            try
            {
                // TODO: Add insert logic here
                _friendService.Add(friend);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Friend/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_friendService.GetFriend(id));
        }

        // POST: Friend/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Friend friend)
        {
            try
            {
                // TODO: Add update logic here
                _friendService.Update(friend);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Friend/Delete/5
        public ActionResult Delete(int id)
        {
            _friendService.Delete(id);
            return RedirectToAction("Index");
        }

        
    }
}

Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("S2 Test", "Index", "Friend", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Friend", "Index", "Friend")</li>
                    <li>@Html.ActionLink("Game", "Index", "Game")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - S2 Test Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>